import type { Metadata } from "next";
import { Geist, Geist_Mono, Wendy_One } from "next/font/google";
import "./globals.css";
import Web3Provider from "./Web3Provider";
import { SessionProvider } from "next-auth/react"
import { headers } from 'next/headers';
import { WagmiProvider, cookieToInitialState } from 'wagmi'
import { getConfig } from '../wagmi';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const param = (await headers()).get('cookie')

  return (
    <html lang="en">
      <head>
        <script src="https://accounts.google.com/gsi/client" async defer />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <Web3Provider param={param}>{children}</Web3Provider>
        </SessionProvider>
      </body>
    </html>
  );
}
